# Generated by Django 3.2.6 on 2021-08-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='business',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
