# Generated by Django 3.2.6 on 2021-08-08 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_announce'),
    ]

    operations = [
        migrations.AddField(
            model_name='announce',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
