# Generated by Django 3.2.6 on 2021-08-08 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_userlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserList',
        ),
    ]
