# Generated by Django 3.2.6 on 2021-08-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_userlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
